### PR TITLE
Server settings first-pass

### PR DESCRIPTION
**Pull request by bostelk**

### CODE REVIEW

**Comment by MajorMJR** [comment]
Thanks these changes are great.  One problem I see is we are making a new server-settings.json file every time the server is started.  Maybe we should check first if the file exists and then use those settings?  I can see some possible issues arising if the server is tried to start but there are issues creating the server-settings.json file.

**Comment by bostelk** [comment]
Well, you need to write _server-settings.json_  because there may have been changes from the frontend.

In the init you could try and load _server-settings.json_ from the factorio directory and use those values as a default.

**Comment by MajorMJR** [comment]
Right I think we should read the server-settings.json file when starting up and use those as defaults.

In the initFactorio function we should check if the server-settings.json file exists and if so use those settings.  If it doesn't exist then we should write the file in that function.  Then when starting the server we can diff the two settings and if there was any modifications from the GUI then load those settings.  Maybe add a dialog asking if you want to save the new settings file?

Usually I'm logged into my Factorio server anyway and make some modification to the file over SSH.  This way both methods of changing the settings would work.

**Comment by MajorMJR** [comment]
I'll merge in these changes as the Windows support looks good.  I should have some time this evening to add in some checks for an existing settings file.

**Pull request merged**
