### PR TITLE
Move login to the api router.

### PR DESCRIPTION
**Pull request by bostelk**
Right, so it turns out having nginx serve /login as a static file and then post to the same location is rather complex. At least, I couldn't find a clear way to route a GET to a static location and then a POST to the proxy.

So, I figured an easier solution would be to move the login POST to the api router (/api/login).

### CODE REVIEW

**Comment by MajorMJR** [comment]
Why did you need to add the middleware function to the Route struct?  Doesn't HandlerFunc already satisfy the interface for http.Handler?

Since http.HandlerFunc can return the http Handler then we can already implement the middleware by creating a function that returns the http.ResponseWriter.

Also run the code through gofmt or goimports to fix the formatting issues.

**Comment by MajorMJR** [comment]
I think it should just be possible to move the /login route to /api/login, I'm not sure if we need to add the extra middleware function since that's already implemented with the HandlerFunc method.  

Using HandlerFunc has the advantage of being able to chain the middleware like CheckSession(LogRequest(http.Request))

**Comment by bostelk** [comment]
Right, so it's there because the _/api/login_ route uses a handler with out the authentication check. So, it required api routes to define if they want authentication or not.

An alternative is to define the _/api/login_ route outside of the api routes list. This way api routes will always wrap their handlers with _CheckAuth_.

**Comment by MajorMJR** [comment]
I would go with the second method, adding the second middleware function makes the HTTP handlers confusing with multiple layers of middleware.

**Comment by MajorMJR** [comment]
Should the name of the CheckSession method be changed to CheckAuth still?  I can't recall if I used it somewhere else in the code.

Was the login working using this method? I think I tried to move this route before and ran into some issues but it looks like it should be working just from looking at the code now.

**Comment by bostelk** [comment]
git grep returned no matches.

yes, give it a try.

**Comment by MajorMJR** [comment]
Thanks looks good.

**Pull request merged**
